// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAueYUVcgR-LWEDAHtDIZyv3ppagYgc6xM',
    appId: '1:583974691550:web:9fbfab2e2545837c79584f',
    messagingSenderId: '583974691550',
    projectId: 'testregister-ae4f8',
    authDomain: 'testregister-ae4f8.firebaseapp.com',
    databaseURL: 'https://testregister-ae4f8.firebaseio.com',
    storageBucket: 'testregister-ae4f8.appspot.com',
    measurementId: 'G-43MVCVRJVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKb5Z8Gt9NHj1eITD5I-fZk788gKy5INQ',
    appId: '1:583974691550:android:fb589993847b199979584f',
    messagingSenderId: '583974691550',
    projectId: 'testregister-ae4f8',
    databaseURL: 'https://testregister-ae4f8.firebaseio.com',
    storageBucket: 'testregister-ae4f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsWfvkk4fos5ILXp3TropAb67o6IptPQY',
    appId: '1:583974691550:ios:20074b2a3ce7317d79584f',
    messagingSenderId: '583974691550',
    projectId: 'testregister-ae4f8',
    databaseURL: 'https://testregister-ae4f8.firebaseio.com',
    storageBucket: 'testregister-ae4f8.appspot.com',
    androidClientId: '583974691550-h72m22ro06q6b2rbfhr4lj6td8822522.apps.googleusercontent.com',
    iosBundleId: 'com.uac.qu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsWfvkk4fos5ILXp3TropAb67o6IptPQY',
    appId: '1:583974691550:ios:f6de673d3a6db26279584f',
    messagingSenderId: '583974691550',
    projectId: 'testregister-ae4f8',
    databaseURL: 'https://testregister-ae4f8.firebaseio.com',
    storageBucket: 'testregister-ae4f8.appspot.com',
    androidClientId: '583974691550-h72m22ro06q6b2rbfhr4lj6td8822522.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAueYUVcgR-LWEDAHtDIZyv3ppagYgc6xM',
    appId: '1:583974691550:web:54f0091675cfeed979584f',
    messagingSenderId: '583974691550',
    projectId: 'testregister-ae4f8',
    authDomain: 'testregister-ae4f8.firebaseapp.com',
    databaseURL: 'https://testregister-ae4f8.firebaseio.com',
    storageBucket: 'testregister-ae4f8.appspot.com',
    measurementId: 'G-MY4X6LDVL9',
  );
}
